/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'diddi' at '10/18/16 9:49 PM' with Gradle 3.1
 *
 * @author diddi, @date 10/18/16 9:49 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
